scenario_user/routes.py
"""В данном модуле содержится описание эндпоинтов для варианта использования работа с запросами"""

# сторонние пакеты
from flask import Blueprint, render_template, current_app, request

# модули проекта
from DB.sql_provider import SQL_Provider
from DB.database import work_with_db
from access import group_permission_decorator


user_app = Blueprint('user_app', __name__, template_folder='templates')
provider = SQL_Provider('scenario_user/sql')


@user_app.route('/')
def user_index():
# меню запросов
    return render_template('menu.html')


@user_app.route('/sql1', methods=['GET', 'POST'])
@group_permission_decorator
def user_sql1():
    # Выполнение первого запроса
    if request.method == 'GET':
        return render_template('sql_1.html')
    else:
        value = request.form.get('value', None)
        if value is not None:
            sql = provider.get('sql1.sql', gener1=value)
            print(sql)
            result = work_with_db(current_app.config['DB_CONFIG'], sql)
            print(result)
            name = [" месяц ", " название товара ", " количество ", " стоимость " ]
            if not result:
                return render_template('error.html')
            return render_template('result_1.html', res=result, name=name)
        else:
            return 'Not found value'


@user_app.route('/sql2', methods=['GET', 'POST'])
@group_permission_decorator
def user_sql2():
    # Выполнение второго запроса
    if request.method == 'GET':
        return render_template('sql_2.html')
    else:
        value1 = request.form.get('value1', None)
        value2 = request.form.get('value2', None)
        name = ["дата ", "общая сумма оплаты"]
        if value1 is not None and value2 is not None:
            sql = provider.get('sql2.sql', gener1=value1, gener2=value2)
            result = work_with_db(current_app.config['DB_CONFIG'], sql)
            if not result:
                return render_template('error.html')
            return render_template('result_2.html', res=result, name=name)
        else:
            return 'Not found value'


@user_app.route('/sql3', methods=['GET', 'POST'])
@group_permission_decorator
def user_sql3():
    # Выполнение третьего запроса
    if request.method == 'GET':
        return render_template('sql_3.html')
    else:
        value1 = request.form.get('value1', None)
        value2 = request.form.get('value2', None)
        name = ["категория ", "материал", "товар ", "дата поставки ", "единица измерения ", "цена ", "количество товара "]
        if value1 is not None and value2 is not None:
            sql = provider.get('sql3.sql', gener1=value1, gener3=value2)
            result = work_with_db(current_app.config['DB_CONFIG'], sql)
            print(result)
            if not result:
                return render_template('error.html')
            print(name)
            return render_template('result_3.html', res=result, name=name)
        else:
            return 'Not found value'

scenario_user/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
    <h3> Результатов по данному запросу не найдено</h3><br>
    <h3> <a href="{{url_for('user_app.user_index')}}"> Вернуться назад</a></h3>


</body>
</html>

scenario_user/templates/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Выберите запрос</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="7" face="Times New Roman">Выберите запрос</font>
<h1>
    <ul>
        <li><a href="{{url_for('user_app.user_sql1')}}">  Отчет об оплате заказа</a></li>
        <li><a href="{{url_for('user_app.user_sql2')}}"> Общая сумма оплаты покупателя</a></li>
        <li><a href="{{url_for('user_app.user_sql3')}}"> Все сведения о самом дорогом заказе </a></li>
    </ul>
    <br>
    <h2><a href="{{url_for('index')}}"> Вернуться назад</a></h2>

</h1>
</body>
</html>

scenario_user/templates/result_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
    <style>
        .main-table{
            border: 5px solid black;
            padding: 10px 15px;
        }

        .text-style{
            text-align: center;
        }
         .main-table-cell {
        border: 2px solid #02585f;
        padding: 5px 10px;
        text-align: center;
      }
    </style>
</head>
<body>
<div class="text-style">
<font size="6" face="Times New Roman">Отчет об оплате заказа</font>
<div class="">
<br>
     <table class="main-table test-style" style="display: inline-block;">
         <thead>
            <tr class="success">
                {% for i in name%}
            <th class="text-center">{{i}}</th>
                {% endfor %}
            </tr>
         </thead>

        <tbody>
            {% for item in res%}
            <tr>
            {% for key, value in item.items() %}
             <td class="main-table-cell"> {{value}} </td>
            {% endfor %}
             </tr>
            {% endfor %}
            </tbody>
    </table>

</div>
    <br>
    <h3>
        <a href="{{url_for('user_app.user_sql1')}}"> Вернуться назад</a>
    </h3>
</div>
</body>
</html>

scenario_user/templates/result_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
    <style>
        .main-table{
            border: 2px solid black;
            padding: 5px 10px;
        }

        .text-style{
            text-align: center;
        }
         .main-table-cell {
        border: 2px solid #02585f;
        padding: 5px 10px;
        text-align: center;
      }
    </style>
</head>
<body>
<div class="text-style">
<font size="6" face="Times New Roman"> Общая сумма оплаты покупателя</font>

    <div>
    <br>
        <table class="main-table test-style" style="display: inline-block;">
         <thead>
            <tr class="success">
                {% for i in name%}
            <th class="text-center">{{i}}</th>
                {% endfor %}
            </tr>
         </thead>

        <tbody>
            {% for item in res%}
            <tr>
            {% for key, value in item.items() %}
             <td class="main-table-cell"> {{value}} </td>
            {% endfor %}
             </tr>
            {% endfor %}
            </tbody>
    </table>
</div>    <br>
        <h3><a href="{{url_for('user_app.user_sql2')}}"> Вернуться назад</a></h3>
</div>
</body>
</html>

scenario_user/templates/result_3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
    <style>
        .main-table{
            border: 2px solid black;
            padding: 5px 10px;
        }

        .text-style{
            text-align: center;
        }
        .main-table-cell {
        border: 2px solid #02585f;
        padding: 5px 10px;
        text-align: center;
      }
    </style>
</head>
<body>
<div class="text-style">
<font size="6" face="Times New Roman">Все сведения о самом дорогом заказе </font>

    <div>
    <br>
        <table class="main-table test-style" style="display: inline-block;">
         <thead>
            <tr class="success">
                {% for i in name%}
            <th class="text-center">{{i}}</th>
                {% endfor %}
            </tr>
         </thead>

            {% for item in res%}
            <tr>
            {% for key, value in item.items() %}
                 <td class="main-table-cell">{{value}}</td>
            {% endfor %}
             </tr>
            {% endfor %}

    </table>
</div>    <br>
    <h3>
        <a href="{{url_for('user_app.user_sql3')}}"> Вернуться назад</a>
    </h3>
</div>
</body>
</html>

scenario_user/templates/sql_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Введите год, по которому нужна информация</font>

<form action="" method="post">
    <br>
    <input type="text" placeholder="Год" name="value">
    <input type="submit" value="Отправить">
    <br>
    <br>
    <h3><a href="{{url_for('user_app.user_index')}}"> Вернуться назад</a></h3>
</form>

</body>
</html>

scenario_user/templates/sql_2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Ввести год и месяц</font>

<form action="{{  url_for('user_app.user_sql2')  }}" method="post">
    <br>
    <input type="text" placeholder="Value1" name="value1">
    <input type="text" placeholder="Value2" name="value2">
<!--    input date можно еще будет сделать-->
    <input type="submit" value="Отправить">
    <br>
    <br>
    <h3><a href="{{url_for('user_app.user_index')}}"> Вернуться назад</a></h3>
</form>

</body>
</html>

scenario_user/templates/sql_3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask course</title>
</head>
<style>
    .text-style{
        text-align: center;
    }
</style>
<body class="text-style">
<font size="6" face="Times New Roman">Введите год и месяц</font>

<form action="{{  url_for('user_app.user_sql3')  }}" method="post">
    <br>
    <input type="text" placeholder="Value1" name="value1">
    <input type="text" placeholder="Value2" name="value2">
<!--    input date можно еще будет сделать-->
    <input type="submit" value="Отправить">
    <br>
    <br>
        <h3><a href="{{url_for('user_app.user_index')}}"> Вернуться назад</a></h3>
</form>

</body>
</html>